# Generated by Django 4.2.6 on 2023-11-30 21:58
# noqa

import django.db.models.deletion
from django.db import migrations, models

import accounts.handlers


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Discount value when 'discount' is True",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(max_length=50),
                ),
                (
                    "zip_code",
                    models.CharField(max_length=15),
                ),
                (
                    "city",
                    models.CharField(max_length=50),
                ),
                (
                    "state",
                    models.CharField(max_length=50),
                ),
                (
                    "country",
                    models.CharField(max_length=50),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="account",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="account",
            old_name="surname",
            new_name="last_name",
        ),
        migrations.AddField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.handlers.image_directory_path,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.accounttype",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.useraddress",
            ),
        ),
    ]
