# Generated by Django 4.2.6 on 2023-12-01 20:31

import django.db.models.deletion
from django.db import migrations, models

import accounts.handlers


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_accounttype_useraddress_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-created_at", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.accounttype",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.useraddress",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the account was created",
                null=True,
                verbose_name="created",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="account",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=accounts.handlers.image_directory_path,
                verbose_name="profile picture",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="surname"),
        ),
        migrations.AlterField(
            model_name="account",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="When the account was updated",
                null=True,
                verbose_name="updated",
            ),
        ),
        migrations.AlterField(
            model_name="accounttype",
            name="discount_value",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Discount value for a user",
                verbose_name="discount",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="state",
            field=models.CharField(
                help_text="The name of the province in which you live`", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="zip_code",
            field=models.CharField(max_length=15, verbose_name="zip code"),
        ),
        migrations.AlterModelTable(
            name="account",
            table="accounts",
        ),
        migrations.AlterModelTable(
            name="accounttype",
            table="account_types",
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
        migrations.AlterModelTable(
            name="useraddress",
            table="addresses",
        ),
    ]
