# Generated by Django 4.2.6 on 2023-12-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="state",
            field=models.CharField(
                help_text="The name of the province in which you live", max_length=50
            ),
        ),
    ]
