# Generated by Django 4.2.6 on 2023-12-02 21:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_account_alter_useraddress_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={"verbose_name_plural": "User addresses"},
        ),
    ]
