# Generated by Django 4.2.6 on 2023-12-03 21:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_user_account_account_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="account",
            new_name="user",
        ),
    ]
