# Generated by Django 4.2.6 on 2023-12-04 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_account_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
        migrations.RemoveField(
            model_name="account",
            name="address",
        ),
        migrations.AddField(
            model_name="accounttype",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
    ]
