# Generated by Django 4.2.6 on 2023-12-04 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0012_remove_account_account_type_remove_account_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttype",
            name="account",
        ),
        migrations.AddField(
            model_name="account",
            name="account_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.account",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.account",
            ),
        ),
    ]
