# Generated by Django 4.2.6 on 2023-12-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_account_account_type_alter_useraddress_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="client_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="Client ID"),
        ),
    ]
