# Generated by Django 4.2.6 on 2024-01-06 15:07

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_account_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
    ]
