# Generated by Django 4.2.6 on 2024-01-06 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_account_phone"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="accounttype",
            table=None,
        ),
        migrations.CreateModel(
            name="UserShippingAdress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=15, verbose_name="zip code")),
                ("city", models.CharField(max_length=50)),
                (
                    "state",
                    models.CharField(
                        help_text="The name of the province in which you live",
                        max_length=50,
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_address",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User shipping addresses",
                "db_table": "shipping_addresses",
            },
        ),
    ]
