# Generated by Django 4.2.6 on 2024-01-09 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_alter_usershippingaddress_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="account_type",
        ),
        migrations.AddField(
            model_name="account",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.accounttype",
            ),
        ),
    ]
