# Generated by Django 4.2.6 on 2024-01-15 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_remove_account_account_type_account_account"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usershippingaddress",
            options={
                "ordering": ["-id"],
                "verbose_name_plural": "User shipping addresses",
            },
        ),
    ]
