# Generated by Django 4.2.6 on 2024-02-04 20:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0020_alter_usershippingaddress_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usershippingaddress",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Name"
            ),
        ),
        migrations.AddField(
            model_name="usershippingaddress",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Surname"
            ),
        ),
        migrations.AddField(
            model_name="usershippingaddress",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
