# Generated by Django 4.2.6 on 2024-02-04 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0022_usershippingaddress_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usershippingaddress",
            name="phone",
        ),
    ]
