# Generated by Django 4.2.6 on 2024-02-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_resetpasswordlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="resetpasswordlink",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When the link was created",
                null=True,
                verbose_name="created",
            ),
        ),
        migrations.AddField(
            model_name="resetpasswordlink",
            name="expiration_time",
            field=models.IntegerField(
                blank=True,
                default=86400,
                null=True,
                verbose_name="Expiration time (in seconds)",
            ),
        ),
        migrations.AddField(
            model_name="resetpasswordlink",
            name="expired",
            field=models.BooleanField(default=False),
        ),
    ]
