# Generated by Django 4.2.6 on 2024-02-19 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0025_resetpasswordlink_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetpasswordlink",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
