# Generated by Django 4.2.6 on 2024-05-21 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0027_alter_resetpasswordlink_expiration_time"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["client_id"], name="accounts_client__a4e301_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(fields=["user"], name="accounts_user_id_6786b5_idx"),
        ),
    ]
