# Generated by Django 4.2.6 on 2024-05-27 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import products.handlers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the category was added",
                        null=True,
                        verbose_name="added",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the category was updated",
                        null=True,
                        verbose_name="updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "categories",
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="ChildSubcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "childsubcategory",
                "verbose_name_plural": "childsubcategories",
                "db_table": "childsubcategories",
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
                "db_table": "subcategories",
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_id",
                    models.IntegerField(unique=True, verbose_name="Product ID"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.handlers.image_directory_path,
                        verbose_name="product picture",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("slug", models.SlugField(max_length=255)),
                ("stock", models.PositiveBigIntegerField()),
                ("in_stock", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the product was added",
                        null=True,
                        verbose_name="added",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the product was updated",
                        null=True,
                        verbose_name="updated",
                    ),
                ),
                (
                    "child_subcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.childsubcategory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "db_table": "products",
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.AddField(
            model_name="childsubcategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products.subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="categories_name_98d7d5_idx"),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(fields=["slug"], name="subcategori_slug_af3bd5_idx"),
        ),
        migrations.AddIndex(
            model_name="subcategory",
            index=models.Index(fields=["name"], name="subcategori_name_3c9410_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id", "slug"], name="products_id_b7370b_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["child_subcategory"], name="products_child_s_06904a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="childsubcategory",
            index=models.Index(fields=["slug"], name="childsubcat_slug_c588f9_idx"),
        ),
        migrations.AddIndex(
            model_name="childsubcategory",
            index=models.Index(fields=["name"], name="childsubcat_name_129e7f_idx"),
        ),
    ]
