# Generated by Django 4.2.6 on 2024-05-21 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-created_at", "name"], "verbose_name": "product"},
        ),
    ]
