# Generated by Django 4.2.6 on 2024-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.IntegerField(unique=True, verbose_name="Product ID"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="categories_name_98d7d5_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="products_name_6f9890_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="products_categor_4083ff_idx"),
        ),
    ]
