# Generated by Django 4.2.6 on 2024-05-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_childsubcategory_slug_alter_subcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childsubcategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="childsubcategories",
                to="products.subcategory",
            ),
        ),
    ]
