# Generated by Django 4.2.6 on 2024-05-28 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_childsubcategory_subcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childsubcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="childsubcategory",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chisubcategories",
                to="products.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
