# Generated by Django 4.2.6 on 2024-06-03 21:13

import django.db.models.deletion
from django.db import migrations, models

import products.handlers


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products.handlers.image_directory_path,
                        verbose_name="product picture",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product images",
                "db_table": "product images",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["id", "product"], name="product ima_id_45822f_idx"
                    )
                ],
            },
        ),
    ]
