# Generated by Django 4.2.6 on 2024-06-03 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_product_image_productimage"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="productimage",
            new_name="product_ima_id_417347_idx",
            old_name="product ima_id_45822f_idx",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="product_images",
        ),
    ]
