# Generated by Django 4.2.6 on 2024-06-03 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0007_rename_product_ima_id_45822f_idx_product_ima_id_417347_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-uploaded_at"], "verbose_name": "product_images"},
        ),
    ]
