# Generated by Django 4.2.6 on 2024-06-13 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0009_rename_product_ima_id_417347_idx_product_ima_id_7164bf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={"ordering": ["-uploaded_at"], "verbose_name": "product_image"},
        ),
        migrations.RenameIndex(
            model_name="productimage",
            new_name="product_ima_id_417347_idx",
            old_name="product_ima_id_7164bf_idx",
        ),
        migrations.AlterModelTable(
            name="productimage",
            table="product_images",
        ),
    ]
