# Generated by Django 4.2.6 on 2024-07-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_productimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="for_sale",
            field=models.PositiveBigIntegerField(
                choices=[
                    (5, "5%"),
                    (10, "10%"),
                    (15, "15%"),
                    (20, "20%"),
                    (25, "25%"),
                    (30, "30%"),
                    (35, "35%"),
                    (40, "40%"),
                    (45, "45%"),
                    (50, "50%"),
                ],
                default=0,
            ),
        ),
    ]
