# Generated by Django 4.2.6 on 2024-07-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_product_for_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reduced_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
    ]
